### ISSUE TITLE
ZBAR

### ISSUE THREAD

**Issue by johan-schoeman** [dm77/barcodescanner#176] opened 2016-02-21 10:49 UTC
I can scan all barcode types with ZBAR except for PDF417. Has anyone had a similar issue and managed to resolve it?

**Comment by dm77** [comment] 2017-08-24 23:59
Unfortunately zbar doesn't really support pdf 417. I have had better luck with ZXing in the past. Closing as a duplicate of #45

**Closed by dm77** 2017-08-24 23:59 UTC
