### ISSUE TITLE
huawei mate8 read qrcode difficulty (华为mate8手机扫码识别困难)

### ISSUE THREAD

**Issue by ethanhua** [dm77/barcodescanner#249] opened 2016-10-21 10:18 UTC
zxing 1.8.4 
On the mate8 phone code recognition difficult 

is Zbar relative to zxing recognition degree  high?
 What is the difference between them?

**Comment by lucid-lynxz** [comment] 2016-12-21 06:29
请问问题解决了吗? 方便给一下方案吗? 谢谢

**Comment by wangyuetingtao** [comment] 2017-01-13 07:15
is your problem resolved？

**Comment by ethanhua** [comment] 2017-01-13 08:50
@wangyuetingtao not yet

**Comment by lazydeer** [comment] 2017-02-08 07:14
@ethanhua 我现在遇到华为的双摄像头的系列手机，也是扫码困难，只要是双摄像头的好像都无法对焦，您的问题解决了吗？

**Comment by lzh0877** [comment] 2017-02-28 02:32
主要原因是因为camera设置的previewsize太小，导致显示的画面极其模糊

**Comment by WeRockStar** [comment] 2017-03-25 06:40
I have a same problem.

**Comment by dm77** [comment] 2017-03-25 20:34
Hi @ethanhua  - Can you tell me if you are using zxing or zbar? Also can you tell me if the sample apps work better or worse? Can you also tell me if the issue has been resolved with 1.9 for you?

**Comment by wangyuetingtao** [comment] 2017-03-30 08:04
add this to manifest.xml   ：

    <uses-feature android:name="android.hardware.camera.autofocus"/>

**Comment by idealcn** [comment] 2017-04-01 07:05
hello,i am from china ,my english is poor,i am sorry.my question is that when scanning ,the scan line dont
move up and down, but just stay at middle of surface view.Could you help to tell me how to solve this problem? thank you very much!

**Comment by ethanhua** [comment] 2017-04-01 07:16
@idealcn 你的问题属于UI上的范围 你自己定义一个view 继承ViewFinderView 去间隔绘制对应的扫码线即可

**Comment by ethanhua** [comment] 2017-04-01 07:23
@dm77   hi !  thank you for respond to me 
1) I used zxing in my project
2) in same mate9 device, wechat app better ;
3) i dont have mate9 now,  i will give you answer later

**Comment by WeRockStar** [comment] 2017-04-01 08:15
@ethanhua I solved this problem with PR https://github.com/dm77/barcodescanner/pull/293

**Comment by cmcdezhh** [comment] 2017-06-13 07:40
I have a same problem in HUAWEI Mate9 with zxing 1.9.3

**Comment by bmbogdan** [comment] 2017-06-13 11:46
This problem occurs even on huawei p8/p9 lite. Any updates?

**Comment by w22ee** [comment] 2017-07-13 07:35
华为p9  华为v8都有这样的问题，可能双摄都有问题

**Comment by dm77** [comment] 2017-07-13 21:55
Closing as a duplicate of #287

**Closed by dm77** 2017-07-13 21:55 UTC
Labels: duplicate
