### ISSUE TITLE
[Bug] An error occurred while connecting to camera: 0

### ISSUE THREAD

**Issue by StErMi** [dm77/barcodescanner#92] opened 2015-06-12 13:01 UTC
I'm using the latest version `me.dm7.barcodescanner:zxing:1.7.2` from Gradle.
I've setup up a sample app following the code of the SimpleScannerActivity with all the correct permissions.

When I open the SimpleScannerActivity I get a blackscreen and this error on the Android Log:

`W/CameraBase﹕ An error occurred while connecting to camera: 0`

How can I fix this issue? Thanks.

**Comment by merijnbrs** [comment] 2015-07-02 12:15
Im facing the exact same thing. but perhaps its a little different. If i open the fragment where the barcodescanner is in, it works. if i open a child fragment and go back, it still works. but if i go to another fragment and back (so in an navigation drawer) then i get the same error.
Its driving me really nuts!

**Comment by Cross22** [comment] 2015-07-02 20:14
When I saw this issue it was because I had added <uses-permission android:name="android.permission.CAMERA" /> to the Application tag, whereas it should be under the manifest tag. Moving it up a line resolved this.

**Comment by jmuthad** [comment] 2015-09-30 16:34
this can also be caused by calling start camera more then once before calling stop.

**Comment by heitorcolangelo** [comment] 2016-03-30 01:55
In my case, I was forgetting to call **scannerView.stopCamera()** and **scannerView = null** in **onDestroy method.**

**Comment by jmuthad** [comment] 2016-03-30 14:32
yeah that's another good way to cause it

**Comment by Robbypatel1357** [comment] 2016-09-28 11:44
Hello my device is Lg Optimus exceed 2 4.4.2.
We already put Camera Permission

**Comment by dm77** [comment] 2017-03-22 06:38
Closing as this doesn't sound like a bug in the library.

**Closed by dm77** 2017-03-22 06:38 UTC

**Comment by sevenbitsriddhi** [comment] 2018-05-14 10:16
my problem solved when I realized I was calling `startcamera` multiple times! Now, My question is, is there any ways that I can check weather the camera is satrted or not?
