### ISSUE TITLE
Scanning an empty QR code stops future QR codes from being detected

### ISSUE THREAD

**Issue by jeroen1602** [dm77/barcodescanner#458] opened 2018-10-30 13:06 UTC
## Observed behavior
When scanning an emtpy barcode the library won't call `handleResult` and any future barcode that is scanned also won't call the `handleResult`

## Intended behavior
The library should call `handleResult` with a Result object that has an empty string as it's contents. It also shouldn't stop any future scans from happening.

## Steps to reproduce
I included a zip file with an example project.
Open the app and try and scan a normal barcode.  
The app should display a Toast with it's contents.  
Now try and scan an empty barcode.  
Nothing seems to happen, but when you try and scan a normal barcode again nothing happens.  
I used this website [www.the-qrcode-generator.com](https://www.the-qrcode-generator.com/) to generate the empty barcode

## System information
Android version: 8.1.0
Library version: 1.9.8
CompileSdk: 28
Support library version: 28.0.0

## Included files
[Barcode.zip](https://github.com/dm77/barcodescanner/files/2529719/Barcode.zip)

**Comment by hienvalax** [comment] 2018-11-15 07:36
Thanks

**Comment by dm77** [comment] 2019-02-17 03:03
I am unable to reproduce the issue with zxing-sample project. Closing the issue as it is not related to the library and probably something do with your project. Feel free to reopen if you think my reasoning is incorrect. Thank you.

**Closed by dm77** 2019-02-17 03:03 UTC
