### ISSUE TITLE
Exception: java.lang.RuntimeException: autoFocus failed

### ISSUE THREAD

**Issue by crissk047** [dm77/barcodescanner#7] opened 2014-04-04 07:21 UTC
Hi,
the barcodescanner initially works fine but after trying to auto focus two to three times i get a RuntimeException: autoFocus failed:

```
java.lang.RuntimeException: autoFocus failed
            at android.hardware.Camera.native_autoFocus(Native Method)
            at android.hardware.Camera.autoFocus(Camera.java:975)
            at me.dm7.barcodescanner.core.CameraPreview$1.run(CameraPreview.java:196)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:213)
            at android.app.ActivityThread.main(ActivityThread.java:5225)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
            at dalvik.system.NativeStart.main(Native Method)

```

any idea how to fix that?
Thanks
Criss

**Comment by localhostEU** [comment] 2015-01-25 06:43
Hello, @dm77. Using latest me.dm7.barcodescanner:zxing:1.6. Problem still persists on some Sony Devices (for example Sony Xperia Z1 - C6903).

**Comment by jodaka** [comment] 2015-02-03 10:11
Any chances for PR#41 to be merged any time soon? I'm also experiencing the same crash as described above on Sony Experia Z.

**Comment by corest** [comment] 2015-04-05 22:12
+1 for merging commit #41

**Comment by plastiv** [comment] 2015-05-19 10:45
Guys, while author is reviewing my change, you can check drop-in replacement which contains latest master + #41. 

```
repositories {
    maven { url "https://raw.github.com/plastiv/barcodescanner/mvn_repo" }
}
dependencies {
    compile 'io.github.plastiv.barcodescanner:zxing:1.7' //  or 1.5 
    compile 'io.github.plastiv.barcodescanner:zbar:1.7'
}
```

**Comment by vytautasgimbutas** [comment] 2015-05-20 13:09
Review is taking quite some time, isn't it?

**Comment by dm77** [comment] 2015-05-20 17:55
@plastiv @vytautasgimbutas Sorry for the delay in merging #41. Its now merged in and version 1.7.1 has  been pushed to maven central.

**Comment by vytautasgimbutas** [comment] 2015-05-21 06:49
Thanks!

**Comment by vandzi** [comment] 2015-05-22 19:17
Is it fixed? I used @plastiv solution but I received crash reports from sony devices:

```
java.lang.RuntimeException: autoFocus failed
       at android.hardware.Camera.native_autoFocus(Camera.java)
       at android.hardware.Camera.autoFocus(Camera.java:1120)
       at me.dm7.barcodescanner.core.CameraPreview$1.run(CameraPreview.java:245)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5135)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by plastiv** [comment] 2015-05-24 14:04
@vandzi Thx for the feedback. Unfortunately, the issue is not resolved if you can reproduce it.
 
I'm curious if we can hide this Exception with try-catch block and still be able to use autofocus. I have seen such approach here: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/camera/AutoFocusManager.java#L107-L110

**Comment by dm77** [comment] 2015-05-28 07:41
@plastiv can you please take a look at this commit to see if it looks right to you?
https://github.com/dm77/barcodescanner/commit/49bbd5b0dcad2f47085439a66fb09592bee331c0

I just tried your suggestion to catch the Runtime error and reschedule autofocus. Unfortunately I do not have a Sony device to test my change. 

Can any of you with a Sony device test this sample APK here: https://www.dropbox.com/s/ttl5g97tpykexdb/zxing-sample.apk?dl=0

Thank you all for your patience.

**Comment by dm77** [comment] 2015-05-28 07:58
According to @paul75 in #85, the fix didn't work :(. Need to spend more time on this over the weekend.

**Comment by Paul75** [comment] 2015-05-28 07:59
Hello,

Thanks a lot !!!!

Great works :)

**Comment by dm77** [comment] 2015-05-28 08:15
@Paul75 sorry I am a little confused now. You mentioned in #85 that the sample APK didn't work :(. Sorry if I misunderstood. Can you once again let me know if it worked or not? Thank you so much.

**Comment by vytautasgimbutas** [comment] 2015-05-28 08:20
The fix in 1.7.1 didn't work. We've temporarily added try { } catch (Exception exception) {} around the line 245 in CameraPreview.java (mCamera.autoFocus(autoFocusCB);) and it seems to work on Sony xperia device, which has been previously crashing.

**Comment by Paul75** [comment] 2015-05-28 08:24
I retest the link and nothing the same bug.

2015-05-28 10:20 GMT+02:00 Vytautas Gimbutas <notifications@github.com>:

> The fix in 1.7.1 didn't work. We've temporarily added try { } catch
> (Exception exception) {} around the line 245 in CameraPreview.java
> (mCamera.autoFocus(autoFocusCB);) and it seems to work on Sony xperia
> device, which has been previously crashing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dm77/barcodescanner/issues/7#issuecomment-106226991>.
>



-- 
Paul

**Comment by dm77** [comment] 2015-05-28 08:32
Thanks @Paul75.

**Comment by dm77** [comment] 2015-05-28 08:34
@vytautasgimbutas Thank you for your input. This is the commit I made: https://github.com/dm77/barcodescanner/commit/49bbd5b0dcad2f47085439a66fb09592bee331c0.

**Closed** 2015-05-28 09:28 UTC

**Comment by yanayzimran** [comment] 2016-11-24 15:43
I see the same problem with the autoFocus failing on a nexus 5x with android 6.0.1

`11-24 17:41:49.765 2431-2431/com.mymoments.mymoments E/CameraPreview: java.lang.RuntimeException: cancelAutoFocus failed
                                                                      java.lang.RuntimeException: cancelAutoFocus failed
                                                                          at android.hardware.Camera.native_cancelAutoFocus(Native Method)
                                                                          at android.hardware.Camera.cancelAutoFocus(Camera.java:1275)
                                                                          at me.dm7.barcodescanner.core.CameraPreview.stopCameraPreview(CameraPreview.java:115)
                                                                          at me.dm7.barcodescanner.core.CameraPreview.surfaceDestroyed(CameraPreview.java:74)
                                                                          at android.view.SurfaceView.updateWindow(SurfaceView.java:566)
                                                                          at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:239)
                                                                          at android.view.View.dispatchDetachedFromWindow(View.java:14551)
                                                                          at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4789)
                                                                          at android.view.ViewGroup.removeAllViews(ViewGroup.java:4735)
                                                                          at me.dm7.barcodescanner.core.BarcodeScannerView.setupLayout(BarcodeScannerView.java:43)
                                                                          at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(BarcodeScannerView.java:87)
                                                                          at com.xxxxxxxxx.xxxxxxxxxx.ui.components.CustomScannerView.CustomScannerView$1.setupCameraPreview(CustomScannerView.java:54)
                                                                          at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:31)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
