### ISSUE TITLE
java.lang.RuntimeException: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by kyze8439690** [dm77/barcodescanner#416] opened 2018-03-03 13:41 UTC
```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:2272)
       at me.dm7.barcodescanner.core.CameraUtils.isFlashSupported(CameraUtils.java:47)
       at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(BarcodeScannerView.java:253)
       at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(BarcodeScannerView.java:190)
       at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:31)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5546)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

Device: Huawei Mate 7
System: Android 6.0

**Comment by silo4** [comment] 2018-03-12 03:40
Is this problem solved?
It happens on my app,too.
The library version is 1.9 .
The device is Huawei 7i  , System is Android 6.0.1

**Comment by dirkam** [comment] 2018-03-26 06:20
I can see the same on various devices

![image](https://user-images.githubusercontent.com/6302839/37889830-897761a0-30ce-11e8-8423-afaa59dc57da.png)

**Comment by yesidlazaro** [comment] 2018-04-20 14:29
same thing in a samsung device with android 7.

**Comment by dirkam** [comment] 2018-04-25 17:42
Is there a workaround to catch this so the app doesn't crash?

**Comment by userhuman** [comment] 2018-07-09 06:36
comment flash. It will working fine. 

I dont know why can not use flash. Maybe we have to find out to another way for do flash.

```
@Onresume
// mScannerView.setFlash(mFlash);
// mScannerView.setAutoFocus(mAutoFocus);
```

**Comment by userhuman** [comment] 2018-07-09 07:13
Now fixed. In the first time I got this error message.

Because of i call this fragment 2 tab. When i change to call just one it's working.

**Comment by imvikasrai** [comment] 2018-11-15 07:18
anyone found the solution?

**Comment by Hitesh12345678** [comment] 2018-11-29 05:29
i have found same issue in my samsung j8

Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1952)
       at me.dm7.barcodescanner.core.CameraUtils.isFlashSupported(CameraUtils.java:47)
       at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(BarcodeScannerView.java:253)
       at com.sadadqa.transfer.qrcode.ScannerFragment.changeFlashMode(ScannerFragment.java:137)
       at com.sadadqa.transfer.qrcode.TransferActivity.onClick(TransferActivity.java:396)
       at android.view.View.performClick(View.java:6205)
       at android.view.View$PerformClick.run(View.java:23653)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by dirkam** [comment] 2018-12-23 17:43
None of the workarounds worked for me.
However, it seems that there is one:
```java
mScannerView.postDelayed(new Runnable() {
                                        @Override
                                        public void run() {
                                                mScannerView.setFlash(true);
                                        }
                                    }, delayMillis);
```
The idea here is that the issue is related the camera resources being busy, so trying to delay the flash activation. Used to have lots of crashes, so far there is none. 1500ms seems to be working, though lower values might work, too.

**Comment by userhuman** [comment] 2018-12-25 16:49
Sometime you have to check about permission. Flash, Camera and others into manifest.xml

**Comment by AnthonyKoueik** [comment] 2020-01-20 09:19
are we going to fix it here ?
how to fix it ? or how can we import shetmobile  repo ?

**Closed** 2020-05-19 05:48 UTC
Labels: wontfix
